[install]
peer = true
production = false
dev = true
optional = true

[install.scopes]
biomejs = "https://registry.npmjs.org/"

[test]
preload = "./tests/setupVitest.js"
environment = "jsdom"

[build]
minify = true
sourcemap = "external"