version: "0.5"
processes:
  mysql:
    command: scripts/init_mysql.sh
    environment:
    - MYSQL_BASEDIR=${MYSQL_BASEDIR}
    - MYSQL_HOME=${PWD}/mysql
    - MYSQL_DATADIR=${PWD}/mysql/data
    - MYSQL_UNIX_SOCKET=${PWD}/mysql/mysql.sock
    - MYSQL_PID_FILE=${PWD}/mysql/mysql.pid
    - MYSQL_TCP_PORT=3309
    - MYSQLX_TCP_PORT=33090
    - MYSQLX_UNIX_SOCKET=${PWD}/mysql/mysqlx.sock
    - PATH=${PATH}
    availability:
      restart: "always"
      backoff:
        initial_delay: 1s
        max_delay: 10s
    readiness_probe:
      exec:
        command: mysqladmin -u root -S ${PWD}/mysql/mysql.sock ping
      initial_delay: 2s
      period: 1s
      timeout: 1s
      success_threshold: 1
      failure_threshold: 10
    shutdown:
      command: mysqladmin -u root -S ${PWD}/mysql/mysql.sock shutdown
      timeout_seconds: 5

  init:
    command: scripts/init_env.sh
    depends_on:
      mysql:
        condition: service_healthy
