version: "0.5"
processes:
  mysql:
    command: ${PWD}/scripts/init_mysql.sh
    environment:
    - MYSQL_BASEDIR
    - MYSQL_HOME
    - MYSQL_DATADIR
    - MYSQL_UNIX_SOCKET
    - MYSQL_PID_FILE
    - MYSQL_TCP_PORT
    - MYSQLX_TCP_PORT
    - MYSQLX_UNIX_SOCKET
    - MYSQL_LOG_FILE
    - PATH
    availability:
      restart: on_failure
      max_restarts: 5
      backoff:
        initial_delay: 5s
        max_delay: 30s
    readiness_probe:
      exec:
        command: ${MYSQL_BASEDIR}/bin/mysqladmin ping -u root -S ${MYSQL_HOME}/mysql.sock --silent
      initial_delay: 2s
      period: 3s
      timeout: 3s
      success_threshold: 1
      failure_threshold: 10
    shutdown:
      command: |
        lsof -i :${MYSQL_TCP_PORT} -sTCP:LISTEN | awk 'NR > 1 {print $2}' | xargs kill -SIGTERM
        rm -f ${MYSQL_PID_FILE} ${MYSQL_UNIX_SOCKET} ${MYSQLX_UNIX_SOCKET}
      timeout_seconds: 30
    limits:
      memory: 1GB
