name: "Setup NodeJS with pnpm cache"
description: "Setup NodeJS with pnpm cache"
inputs:
  node_version:
    description: "NodeJS Version"
    required: true
  pnpm_version:
    description: "PNPM Version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - name: Setup pnpm cache
      uses: actions/cache@v4.2.0
      with:
        path: |
          ~/.cache/Cypress
          node_modules
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: pnpm --frozen-lockfile recursive install
