name: "Setup NodeJS"
description: "Setup NodeJS"
inputs:
  node_version:
    description: "NodeJS Version"
    required: true
  pnpm_version:
    description: "PNPM Version"
    required: true
  force_install:
    description: "Force install dependencies and Cypress"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
    - name: Setup pnpm & install deps
      uses: pnpm/action-setup@v4
      with:
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
    - name: Force install Cypress
      if: inputs.force_install == 'true'
      shell: bash
      run: pnpx cypress install --force
